BEGIN;

ALTER TABLE content.source_endpoints
  ADD COLUMN IF NOT EXISTS robots_disallowed BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS blocked_until TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS block_reason TEXT,
  ADD COLUMN IF NOT EXISTS block_count INT NOT NULL DEFAULT 0;

COMMIT;